# ---------------------------
# Hexo Theme Solitude
# Author: 伍十七(@everfu)
# Github: https://github.com/everfu/hexo-theme-solitude
#
# Guide: https://solitude.js.org
# 指南：https://solitude.js.org/zh
# ---------------------------

### Basic configuration

# --------------------------- start ---------------------------
# 网站信息
site:
  name:
    class: text
    custom: Xin'Blog
  icon: /favicon.ico
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 导航栏
nav:
  group:

  menu:

  home: /
  categories: /categories
  archives: /archives
  tags: /tags

  right:
    random: false
    custom:
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 首页顶部横幅
hometop:
  enable: false
  banner:
    title: 分享技术<br >与科技生活
    desc:
      许多话，只是写给本身看，仅此罢了。
    icon:
  group:
  recommendList:
    enable: true
    sup: 置顶
    title: Xin'Blog
    url: https://www.joexin.cn
    img: /img/default.avif
    color: "none"

carousel: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 侧边栏
aside:
  home:
    noSticky: "about"
    Sticky: "allInfo"
  post:
    noSticky: "about"
    Sticky: "newestPost"
  page:
    noSticky: "about"
    Sticky: "newestPost,allInfo"
  position: 1

  my_card:
    author:
      img: /img/logo.png
      sticker:
    description: 许多话，只是写给本身看，仅此罢了。
    content:
    state:
      morning: ✨ 早上好，新的一天开始了
      noon: 🍲 午餐时间
      afternoon: 🌞 下午好
      night: 早点休息
      goodnight: 晚安 😴
    witty_words:
    information:

  toc:
    post: true
    page: false
    vague: true

  tags:
    enable: false
    limit: 20
    highlight_list:

  siteinfo:
    postcount: true
    wordcount: false
    pv: true
    uv: true
    updatetime: true
    runtimeenable: true
    runtime: "2023-04-20 00:00:00"
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 页面默认设置
page:
  error: true
  tags: true
  categories: true
  archives: 0
  default:
    cover:
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 文章默认设置
post:
  default:
    cover:
    locate: China
    copyright:
      enable: true
      author: /img/logo.png
      license: CC BY-NC-SA 4.0
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans
  ai:
    enable: false
    modelName: 小七 GPT
  meta:
    date: false
    updated: false
    locate: false
    wordcount: false
    readtime: false
    pv: true
    comment: false
  award:
    enable: false
    appreciators: /about/
    title:
    desc:
    list:
  share:
    enable: false
    list:
  rss: /atom.xml
  covercolor:
    enable: false
    mode: local
    api: https://api.qjqq.cn/api/Imgcolor?img=
    time: 43200000
  footer:
    enable: false
    desc:
    button:
      enable: true
      name:
      url: /about/
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 主题配色
theme_color:
  dark: "#ffc848"
  light: "#425AEF"
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 显示模式
display_mode:
  type: auto
  universe: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 字体
font:
  font-size: 16px
  code-font-size: 16px
  font-family: "PingFang SC, Hiragino Sans GB, Microsoft YaHei, sans-serif"
  code-font-family: '"monospace", monospace'
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 背景图片
background:
  enable: false
  opacity: .2
  dark: https://i.pinimg.com/originals/d8/b3/9d/d8b39d12b653810db452c437211aeb2e.png
  light: https://i.pinimg.com/originals/93/57/38/935738ed9657b296c2ef0ebd2151eb66.jpg
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 页面离开标题诱惑
lure:
  enable: false
  jump: 404 Not Found
  back: ヾ(≧∇≦*)ゝHey, hey, you fell for it.
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 文章过期提醒
expire:
  enable: false
  time: 30
  position: top
  text_prev: "This article expired "
  text_next: " day ago, if the content does not match, please contact the webmaster to update it."
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 首页文章布局
index_post_list:
  direction: column
  column: 2
  cover: both
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 相关文章
related_post:
  enable: false
  limit: 2
  date_type: created
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 自定义右键菜单
right_menu:
  enable: false
  commentBarrage: false
  ctrlOriginalMenu: false
  translate: false
  custom_list:
# --------------------------- end -----------------------

# --------------------------- start ---------------------------
# 复制版权
copy:
  enable: false
  copyright:
    enable: false
    limit: 50
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 图表
mermaid: false
chart: false
typeit: false
# --------------------------- end ---------------------------

### 扩展配置

# --------------------------- start ---------------------------
# 控制台
console:
  enable: false
  recentComment:
    enable: false
    storage: .2
  card:
    tags: true
    archive: "month"
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 简繁体切换
translate:
  enable: true
  defaultEncoding: 2
  translateDelay: 0
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 右下角悬浮导航
rightside:
  enable: false
  percent: false
  hide:
    enable: false
    translate: false
    mode: false
    aside: false
# --------------------------- start ---------------------------

# --------------------------- start ---------------------------
# 页脚
footer:
  information:
    author: false
    left:
    right:
  group:
  randomlink: false
  beian:
  links:
    - name: RSS
      url: /atom.xml
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 404 页面
errorpage:
  img: /img/404.avif
  text: =awa= Page Not Found
  recommendList: true
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 音乐 API
meting_api: "https://meting.qjqq.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r"
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 悬浮音乐
capsule:
  enable: false
  id: 5144842535
  server: netease
  type: playlist
  volume: 0.8
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 快捷菜单
keyboard:
  enable: false
  list:
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 图片懒加载
lazyload:
  enable: false
  field: site
  placeholder: ""
  errorimg: /img/error_load.avif
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 加载动画
loading:
  fullpage: false
  favicon: /img/favicon.png
  pace: true
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 代码高亮
highlight:
  enable: true
  limit: 200
  copy: true
  expand: true
  theme: mac
  color: default
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 图片灯箱
lightbox: false
fancybox: false
mediumZoom: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 纪念日全站变灰
memorial:
  enable: false
  date:
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# OpenGraph
OpenGraph:
  enable: false
  options:
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 字数统计
wordcount: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# Latex 公式
katex:
  enable: false
  per_page: false
  copytex: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 站点验证
verify_site:
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# CSS 前缀
css_prefix: false
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 自定义插入代码
extends:
  head:
  body:
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# PWA
pwa:
  enable: false
  manifest: /manifest.json
  theme_color: "#006a73"
  mask_icon: /img/pwa/favicon.png
  apple_touch_icon: /img/pwa/favicon.png
  bookmark_icon: /img/pwa/favicon.png
  favicon_32_32: /img/pwa/favicon_32.png
  favicon_16_16: /img/pwa/favicon_16.png
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 评论 & LeanCloud 访问量适配
comment:
  use:
  commentBarrage: false
  lazyload: false
  count: false
  sidebar: false
  pv: true
  avatar: https://gravatar.com/avatar
  hot_tip:
    enable: false
    count: 3
  newest_comment:
    enable: true
    storage: .5
    limit: 5

twikoo:
waline:
valine:
  appId: AWUJspJ0osglcFpiek5dQwbS-gzGzoHsz
  appKey: qqOWPqnnAonFrWt3WJm8UcRs
  serverURLs:
  avatar:
  visitor: false
  style: true
  option:
artalk:
giscus:
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 搜索
search:
  enable: false
  type:
  tags:
  algolia:
  local:
    preload: false
    CDN:
  docsearch:
    appId:
    apiKey:
    indexName:
    option:
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 音乐馆
music:
  enable: false
  id: 5144842535
  server: netease
  type: playlist
  volume: 0.8
  mutex: true
  order: list
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 弹幕留言
envelope:
  enable: false
  line: 10
  speed: 20
  hover: true
  loop: true
  page: /message/
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 短文
brevity:
  enable: false
  home_mini: false
  music: false
  page: /essay/
  style: 1
  strip: 30
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 最近评论
recent_comments:
  enable: false
  limit: 50
  cache: 0.2
  page: /recentcomments/
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 不蒜子
busuanzi: false
busuanzi_use: 0
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# 谷歌广告
google_adsense:
  enable: false
  auto_ads: false
  enable_page_level_ads: true
  aside_card: true
  post_card: true
  post_content: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client:
  slot:
# --------------------------- end ---------------------------

# --------------------------- start ---------------------------
# CDN 配置
CDN:
  internal: local
  third_party: custom
  version: true
  custom_format: https://fastly.jsdelivr.net/npm/${name}@${version}/${min_file}
  options:
# --------------------------- end ---------------------------